### ISSUE TITLE
(Suggestion) A way to remove patterns from blocks?

### ISSUE THREAD

**Issue by Revemohl** [Aarronmc/WallpaperCraft#3]
Just something to make it easier to try various designs and store wallpaper blocks more efficiently. How about crafting any patterned block together with a blank press to go back to a solid colored block?

**Comment by Aarronmc** [comment]
Thats a great idea! I'll work on that right away.

**Comment by Aarronmc** [comment]
This has been implemented and will be available in the next public build.
