### ISSUE TITLE
Config Spelling Error

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Aarronmc/WallpaperCraft#4]
# Setting this to true will hide all WallpaperCraft sub colours and will only show the firstcolour option for each block(note these will still be availabvle in the creative inventory and will still be craftable). [default: false]
    B:hidefromJEI=false
}

**Comment by P3rf3ctXZer0** [comment]
Just thought I would let you know XD

**Comment by Aarronmc** [comment]
This was fixed in d76dce828145ca108c635d215f08f8b21dee7683
