### ISSUE TITLE
Guide Book Mod Crash

### ISSUE THREAD

**Issue by WenXin20** [Aarronmc/WallpaperCraft#6]
Forge 1.10.2-2209
[Guide Book](https://minecraft.curseforge.com/projects/guide-book/files) v1.6.3
This is a mod similar to JEI, but uses a book. When I open the Guide Book with this mod, it crashes the game.
[Crash Log](https://minecraft.curseforge.com/linkout?remoteUrl=http%253a%252f%252fpastebin.com%252fzZygCDza)

**Comment by Aarronmc** [comment]
This is related to the same bug causing #5 
This has been fixed and will be resolved in the next public build.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by Aarronmc** [comment]
Just pushed an update. Available now on curse forge.
